### ISSUE TITLE
Responsive menu

### ISSUE THREAD

**Issue by muslih** [kodingbareng/rabaquran#1]
bang @aditiapratama  untuk menu responsive nya apa seperti default bootstrap saja atau seperti wkopi?

**Comment by aditiapratama** [comment]
wah seperti wkopi boleh banget bro @muslih, eniwei itu instagram ada update API baru, jadi kagak ketampil di wkopi image2nya

**Comment by muslih** [comment]
siap bang, menu yang ada saya hapus ya...
